"""
Direct LLM baseline (paper, "Direct LLM baseline", "Comparison with direct LLM generation", Table 3).

"The two settings used the same selection model, prompt, decoding settings, and random
seeds, and they differed only in the source of the 20 candidates passed to the labeling
step. ... In the direct setting, the LLM was called twice, first to generate 20 candidate
codes for the query from its own knowledge and then to label each generated candidate
with the same prompt and decision rule used in the pipeline."

  call 1  generation: the LLM lists 20 CPT codes
  call 2  labeling  : build_prompt / parse_label_response / tau imported from stage3_select

Usage (one run = one seed):
  python baseline_direct_llm.py --models llama3,qwen3 --seed 0 --save_dir results/direct_llm/run_0
  # with the list of CPT codes deleted in past releases (hallucination check, see below):
  python baseline_direct_llm.py ... --deleted_codes data/deleted_cpt_codes.txt

Outputs (save_dir):
  predictions.csv       pre_selection_codes (generated), label_map, retrieved_codes, halluc_codes
  per_query_metrics.csv
  summary_metrics.csv   Recall / Precision / Leakage + n_generated, n_hallucinated, hallucination_rate

Changes from the original code (SunnyBrook/Final/run_llm_only.py)
-----------------------------------------------------------------
Unchanged: generation prompt and example, 20 candidates, code parser, labeling through the
stage-3 functions, 127-query filter, lower-cased query, Has Exclusion routing.

[changed] Hallucination follows the paper's two checks (metrics.is_hallucinated): CPT format,
          and membership in current ∪ deleted codes. The original only checked membership in
          the 8,745-code corpus. Pass the deleted-code list with --deleted_codes; without it
          the reference set is the current corpus only (same as the original).
[added]   Per-run hallucination rate in summary_metrics.csv.
[changed] Sampling is the default (same as stage 3).
[changed] method name llm_only__sel_llama3__ours -> direct_llm__llama3.
[changed] parse_codes() moved here from run_selection_eval.py (only used here).
[removed] Prompt modes nofew / simple / relative, --n_candidates 0 (no cap),
          --no_gen_few_shot, --from_db corpus loading, column-name flags.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import List

import pandas as pd

from build_index import load_cpt_corpus
from config import HAS_EXCLUSION_COL, RESULTS_DIR, TAU, TEMPERATURE, VAL_DATA
from metrics import codes_at_tau, is_hallucinated, load_code_set, save_outputs
from stage1_retrieve import base_record, load_queries
from stage2_rerank import load_cpt_descriptions
from stage3_select import (
    LocalLLM, build_prompt, evaluate_label_maps, label_map_json, parse_label_response, resolve_model,
)

N_CANDIDATES = 20     # same budget as the 20 reranked candidates

# Generation prompt (unchanged)
_GEN_FEWSHOT = """Examples:
Query: laparoscopic cholecystectomy
Codes: ["47562", "47563", "47564"]
"""

_GEN_PROMPT = """You are a medical coding expert building a surgical cohort.
For the query below, list {count} CPT codes (5-digit) that could apply,
including the primary procedure and closely related codes.
{few_shot}
Query: {query}

Return ONLY a JSON list of CPT code strings. Example: ["47562", "47563"]
Codes:"""


def generation_prompt(query: str, n: int = N_CANDIDATES) -> str:
    return _GEN_PROMPT.format(count=f"the {n} most relevant", query=query, few_shot=_GEN_FEWSHOT)


def parse_codes(text: str) -> List[str]:
    """JSON list of codes; falls back to scanning for CPT-shaped tokens. (unchanged)"""
    m = re.search(r"\[[^\]]*\]", text, re.DOTALL)
    if m:
        try:
            arr = json.loads(m.group(0))
            return [str(c).strip() for c in arr if re.fullmatch(r"\d{5}[FTU]?", str(c).strip())]
        except (json.JSONDecodeError, TypeError):
            pass
    return re.findall(r"\b\d{5}[FTU]?\b", text)


def hallucination_summary(pred: pd.DataFrame) -> pd.DataFrame:
    """
    [added] Share of generated codes that are hallucinated, pooled over all queries of a run
    (paper: "61.4% (4.4) of the codes generated by Llama3-8B were classified as hallucinated";
    the (4.4) is the SD over the three runs, from aggregate_runs.py).
    """
    rows = []
    for method, g in pred.groupby("method", sort=False):
        n_gen = int(g["pre_selection_codes"].apply(len).sum())
        n_hal = int(g["halluc_codes"].apply(len).sum())
        rows.append({"method": method, "n_generated": n_gen, "n_hallucinated": n_hal,
                     "hallucination_rate": n_hal / n_gen if n_gen else 0.0})
    return pd.DataFrame(rows)


def main():
    ap = argparse.ArgumentParser(description="Direct LLM baseline: generate + label, no retrieval.")
    ap.add_argument("--data", default=str(VAL_DATA))
    ap.add_argument("--save_dir", default=str(RESULTS_DIR / "direct_llm" / "run_0"))
    ap.add_argument("--models", default="llama3,qwen3")
    ap.add_argument("--llama3_path", default=None)
    ap.add_argument("--qwen3_path", default=None)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--temperature", type=float, default=TEMPERATURE)
    ap.add_argument("--greedy", action="store_true")
    ap.add_argument("--tau", type=int, default=TAU)
    ap.add_argument("--tau_list", default=str(TAU))
    ap.add_argument("--deleted_codes", nargs="*", default=[],
                    help="file(s) of CPT codes deleted in past releases (.txt/.csv/.xlsx)")
    ap.add_argument("--device", default=None)
    ap.add_argument("--max_rows", type=int, default=None)
    args = ap.parse_args()

    queries = load_queries(args.data, max_rows=args.max_rows)
    reference = set(load_cpt_corpus()["code"].astype(str)) | load_code_set(args.deleted_codes)
    print(f"[reference] {len(reference)} codes (current corpus"
          f"{' + deleted codes' if args.deleted_codes else ' only'})")
    code2text = load_cpt_descriptions(strip=False)
    paths = {"llama3": args.llama3_path, "qwen3": args.qwen3_path}

    rows = []
    for alias in [m.strip() for m in args.models.split(",") if m.strip()]:
        llm = LocalLLM(resolve_model(alias, paths), device=args.device, do_sample=not args.greedy,
                       temperature=args.temperature, seed=args.seed)
        for i, (_, r) in enumerate(queries.iterrows(), start=1):
            rec = base_record(r)
            query = rec["query"]
            excl = str(r.get(HAS_EXCLUSION_COL, "")).strip().upper() in {"Y", "YES", "TRUE", "1"}

            # call 1: generate candidates (duplicates removed, capped at 20)
            cand = list(dict.fromkeys(parse_codes(llm.generate(generation_prompt(query)))))[:N_CANDIDATES]

            # call 2: label with the stage-3 prompt and parser
            labels = parse_label_response(llm.generate(build_prompt(query, cand, code2text, excl)), cand) \
                if cand else {}

            rows.append({"method": f"direct_llm__{alias}", **rec,
                         "seed": args.seed,
                         "has_exclusion_flag": excl,
                         "pre_selection_codes": cand,
                         "label_map": label_map_json(labels, cand),
                         "retrieved_codes": codes_at_tau(cand, labels, args.tau),
                         # [changed] paper's hallucination checks (was: c not in corpus)
                         "halluc_codes": [c for c in cand if is_hallucinated(c, reference)]})
            if i % 20 == 0:
                print(f"  [{alias}] {i}/{len(queries)}")
        llm.unload()

    pred = pd.DataFrame(rows)
    save_dir = Path(args.save_dir)
    save_dir.mkdir(parents=True, exist_ok=True)
    pred.to_csv(save_dir / "predictions.csv", index=False)
    print(f"[SAVED] {save_dir / 'predictions.csv'}")

    tau_list = [int(t) for t in args.tau_list.split(",") if t.strip()]
    per_query, summary = evaluate_label_maps(pred, tau_list)
    summary = summary.merge(hallucination_summary(pred), on="method", how="left")   # [added]
    save_outputs(per_query, summary, save_dir)


if __name__ == "__main__":
    main()
